[metadata]
git_commit = "7042664"
overall_exec = "67.35%"
overall_pass = "64.71%"
date = "2024-07-26_15-51-50"

[prompt_results.add_yearmonth]
cost = 0.037752
executed = true
examples_executed = 4
prompt_label = "add_yearmonth"
unit_tests_count = 4
examples_count = 4
parsed = true
elapsed_seconds = 8.432934592
unit_tests_passed = 4

[prompt_results.audi_filter]
cost = 0.036321
executed = true
examples_executed = 2
prompt_label = "audi_filter"
unit_tests_count = 5
examples_count = 2
parsed = true
elapsed_seconds = 8.209253871
unit_tests_passed = 5

[prompt_results.count_model_rows]
cost = 0.036084000000000005
executed = true
examples_executed = 2
prompt_label = "count_model_rows"
unit_tests_count = 5
examples_count = 2
parsed = true
elapsed_seconds = 7.935319554
unit_tests_passed = 5

[prompt_results.weather_data_analyzer]
cost = 0.045015
executed = true
examples_executed = 4
prompt_label = "weather_data_analyzer"
unit_tests_count = 5
examples_count = 5
parsed = true
elapsed_seconds = 12.470379851
unit_tests_passed = 3

[prompt_results.FloatWithUnits]
cost = 0.035691
executed = true
examples_executed = 2
prompt_label = "FloatWithUnits"
unit_tests_count = 3
examples_count = 2
parsed = true
elapsed_seconds = 5.888616199
unit_tests_passed = 3

[prompt_results.clean_column]
cost = 0.03531
executed = true
examples_executed = 3
prompt_label = "clean_column"
unit_tests_count = 5
examples_count = 3
parsed = true
elapsed_seconds = 8.710825313
unit_tests_passed = 5

[prompt_results.event_scheduler]
cost = 0.041259
executed = true
examples_executed = 5
prompt_label = "event_scheduler"
unit_tests_count = 5
examples_count = 5
parsed = true
elapsed_seconds = 9.735732437
unit_tests_passed = 5

[prompt_results.extract_julia_code]
cost = 0.039198
executed = true
examples_executed = 1
prompt_label = "extract_julia_code"
unit_tests_count = 5
examples_count = 4
parsed = true
elapsed_seconds = 6.868172679
unit_tests_passed = 1

[prompt_results.ispersonal]
cost = 0.04256700000000001
executed = false
examples_executed = 0
prompt_label = "ispersonal"
unit_tests_count = 5
examples_count = 4
parsed = false
elapsed_seconds = 10.694945723
unit_tests_passed = 0

[prompt_results.keep_only_names]
cost = 0.035739
executed = true
examples_executed = 4
prompt_label = "keep_only_names"
unit_tests_count = 5
examples_count = 4
parsed = true
elapsed_seconds = 10.664376696
unit_tests_passed = 5

[prompt_results.pig_latinify]
cost = 0.043884000000000006
executed = true
examples_executed = 2
prompt_label = "pig_latinify"
unit_tests_count = 5
examples_count = 4
parsed = true
elapsed_seconds = 10.558300705
unit_tests_passed = 2

[prompt_results.q_and_a_extractor]
cost = 0.040746000000000004
executed = true
examples_executed = 2
prompt_label = "q_and_a_extractor"
unit_tests_count = 5
examples_count = 3
parsed = true
elapsed_seconds = 8.39766529
unit_tests_passed = 0

[prompt_results.timezone_bumper]
cost = 0.052698
executed = false
examples_executed = 0
prompt_label = "timezone_bumper"
unit_tests_count = 5
examples_count = 5
parsed = false
elapsed_seconds = 21.937887908
unit_tests_passed = 0

[prompt_results.wrap_string]
cost = 0.040554
executed = true
examples_executed = 2
prompt_label = "wrap_string"
unit_tests_count = 6
examples_count = 2
parsed = true
elapsed_seconds = 9.332232864
unit_tests_passed = 6
